apiVersion: batch/v1
kind: Job
metadata:
  name: content-upload-job
spec:
  template:
    spec:
      containers:
      - name: uploader
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - echo "<h1>Hello from NFS!</h1>" > /mnt/data/index.html; sleep 10
        volumeMounts:
        - name: web-content
          mountPath: /mnt/data
      restartPolicy: Never
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: nfs-pvc
  backoffLimit: 4
